### ISSUE TITLE
Add support to load depth for ISIIS images

### ISSUE THREAD

**Issue by danellecline** [mbari-org/aidata#12]
Add support to parse and load depth from ISIIS images file names, e.g.

`CFE_ISIIS-001-2023-07-12 09-30-36.364_0001_13.2m.jpg
`
would be 13.2
 
@flecaros-mbari  please comment if I am missing anything
@duane-edgington can you add the depth field to the CFE project on mantis
```[tasklist]
### Tasks
- [x] add attribute depth, a float, to the media type image, on project 902111_CFE
- [x] Add depth as float to the [config/config_uav.yaml ](https://github.com/mbari-org/aidata/blob/main/aidata/config/config_cfe.yml) in the tator:image section
- [x] Revise [plugins/extractors/tap_cfe_media.py](https://github.com/mbari-org/aidata/blob/main/aidata/plugins/extractors/tap_cfe_media.py) to support regexp to parse out depth
- [x] Run pytest in test_load_media.py to verify works
- [x] Replace in-place all existing loaded images with the depth
```
