### ISSUE TITLE
Add support for planktivore labeled training data

### ISSUE THREAD

**Issue by danellecline** [mbari-org/aidata#16]
Add loading support for planktivore training data.

Data is on Project library at  smb://atlas.shore.mbari.org/ProjectLibrary/902004_Planktivore/Data/StevenInternship/Training_Data
 
```[tasklist]
### Tasks
- [x] Add ProjectLibrary mount to mantis
- [ ] Add config for planktivore
- [ ] Add test for planktivore media/ROI load
```
